name: test_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider:
  path:
  flutter_local_notifications: ^0.8.4+3
  cupertino_icons: ^0.1.2
  sensors: ^0.4.1+3
  local_auth: ^0.6.0+1
  geolocator: ^5.1.5
  auto_size_text: ^2.1.0
  device_info: ^0.4.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
      - asset: fonts/Product_Sans_Regular.ttf
      - asset: fonts/Product_Sans_Italic.ttf
        style: italic
      - asset: fonts/Product_Sans_Bold.ttf
        weight: 700